insert into COURSE (title) values ('Nagoya Institute of Technology');
insert into COURSE (title) values ('Necmettin Erbakan University');
insert into COURSE (title) values ('Wake Forest University');
insert into COURSE (title) values ('National University of Internal Affairs');
insert into COURSE (title) values ('Spertus Institute of Jewish Studies');
insert into COURSE (title) values ('Technological University (Dawei)');
insert into COURSE (title) values ('Benemerita Universidad Autónoma de Puebla');
insert into COURSE (title) values ('Ecole Française de Papeterie et des Industries Graphiques');
insert into COURSE (title) values ('Birmingham City University');
insert into COURSE (title) values ('University of South Carolina - Sumter');
insert into COURSE (title) values ('University of Nevada - Reno');
insert into COURSE (title) values ('Daemen College');
insert into COURSE (title) values ('Shenyang Pharmaceutical University');
insert into COURSE (title) values ('Lutherische Theologische Hochschule Oberursel');
insert into COURSE (title) values ('University of Veterinary Science');
insert into COURSE (title) values ('Chadron State College');
insert into COURSE (title) values ('St. Francis College, Brooklyn Heights');
insert into COURSE (title) values ('Universidad Gran Mariscal de Ayacucho');
insert into COURSE (title) values ('Lewis-Clark State College');
insert into COURSE (title) values ('University of Massachusetts at Boston');
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('http://netvibes.com', 9);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('https://live.com', 7);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('https://yahoo.com', 2);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('https://last.fm', 2);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('https://youtu.be', 11);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('https://ucsd.edu', 11);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('http://nymag.com', 5);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('https://google.ca', 1);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('https://fc2.com', 1);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('http://wikia.com', 8);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('https://instagram.com', 20);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('https://hugedomains.com', 6);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('http://dot.gov', 12);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('https://census.gov', 10);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('https://nhs.uk', 8);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('https://rakuten.co.jp', 19);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('http://ifeng.com', 18);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('https://ed.gov', 19);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('https://mediafire.com', 7);
insert into COURSE_MATERIAL (URL, COURSE_ID) values ('https://scientificamerican.com', 14);
